<?php
/**
 * Yireo FormApi for Magento
 *
 * @package     Yireo_FormApi
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2012 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

$field = $this->getField();
?>
<div class="<?php echo $field->getFieldsetName(); ?>-<?php echo $field->getName(); ?>">
    <div class="field field-name-<?php echo $field->getName(); ?>">

        <?php if($field->getData('required')) :?>
        <label for="<?php echo $field->getData('id'); ?>" class="required"><em>*</em><?php echo $field->getLabel(); ?></label>
        <?php else: ?>
        <label for="<?php echo $field->getData('id'); ?>"><?php echo $field->getLabel(); ?></label>
        <?php endif; ?>

        <div class="input-box">
            <?php echo $field->getHtml(); ?>
        </div>
    </div>
</div>