<?php
/**
 * Yireo FormApi for Magento
 *
 * @package     Yireo_FormApi
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2012 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

$form = $this->getForm();

$enctype = ($form->getFeature('upload') == 1) ? ' enctype="multipart/form-data"' : null;
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form action="<?php echo $form->getPostUrl(); ?>" <?php echo $enctype; ?>method="post" name="<?php echo $form->getFormName(); ?>" id="<?php echo $form->getFormId(); ?>">

    <?php foreach($form->getFieldsets() as $fieldset) : ?>
        <?php echo Mage::helper('formapi/template')->getFieldsetBlock($fieldset); ?>
    <?php endforeach; ?>

    <div class="buttons-set">
        <p class="required">* <?php echo $this->__('Required Fields'); ?></p>
        <p class="back-link"><a href="#" onclick="history.go(-1);"><small>&laquo; </small><?php echo $this->__('Back'); ?></a></p>
        <?php echo $form->getField('submit'); ?>
        <?php echo $form->getField('reset'); ?>
    </div>

    <?php echo $this->getBlockHtml('formkey'); ?>
</form>