<?php
/**
 * Yireo FormApi for Magento
 *
 * @package     Yireo_FormApi
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2012 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

$field = $this->getField();
$attributes = $field->getAttributes();
?>
<input <?php echo Mage::helper('formapi/field')->toAttributeString($attributes); ?> />

<?php if($field->getParam('show_description', 1) && $field->hasData('description')) : ?>
<div class="description">
    <p class="note">
        <span>
           <?php echo $field->getData('description'); ?>
        </span>
    </p>
</div>
<?php endif; ?>